### PR TITLE
lanetix/issues#2360: added shouldFilterAccounts permission check

### PR DESCRIPTION
**Pull request by kyspy**

### CODE REVIEW

**Comment by scarney81** [comment]
Couple of things that will need to be done prior to publishing to NPM
- Increment `PATCH` number on version
- Create a new tag for the version: `git tag -a vX.X.X -m 'version X.X.X'` (once merged)

Also, be sure to publish to `npm` as the `lanetix` account.

Let me know if you need help and we can walk through it when I'm in SF. :)

**Comment by scarney81** [comment]
:sheep:

**Comment by kyspy** [comment]
@scarney81 Took care of the first two comments -- Not sure how to publish to `npm` as the `lanetix` account. I have some other work that needs to be finished for PeoplEase by Monday that relies on this change -- is it possible to go over this quickly today or tomorrow? Thanks!

**Comment by kyspy** [comment]
@scarney81 Nevermind figured it out! 1.0.2! https://www.npmjs.com/package/lanetix-authorization

**Pull request merged**
